## Rust

[repos."https://github.com/rust-lang/rust.wiki.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = false
topics = ["rust", "wiki"]

[repos."https://github.com/rust-unofficial/awesome-rust.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = false
topics = ["rust", "awesome"]

[repos."https://github.com/actix/actix-web.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = false
topics = ["rust", "rust_lib", "web"]

## Python

[repos."https://github.com/vinta/awesome-python.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = false
topics = ["python", "awesome"]

[repos."https://github.com/django/asgiref.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = false
topics = ["python", "python_lib", "django", "asgi", "web"]

## Crystal

[repos."https://github.com/crystal-lang/crystal.wiki.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = false
topics = ["crystal", "wiki"]

[repos."https://github.com/veelenga/awesome-crystal.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = false
topics = ["crystal", "awesome"]

## Elixir

[repos."https://github.com/h4cc/awesome-elixir.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = false
topics = ["elixir", "awesome"]

## docs

[repos."https://github.com/zealdocs/zeal.wiki.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = false
topics = ["docs", "wiki"]

## gist::python

[repos."https://gist.github.com/maximilianhurl/cb5507354fc8be812c1e3a578627001f.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = true
topics = ["python_lib", "apistar", "sqlalchemy", "demo"]

## gist::configuration

[repos."https://gist.github.com/njsmith/78f68204c5d969f8c8bc645ef77d4a8f.git"]
vcs = "git"
allow_sync = true
bare = false
use_proxy = true
topics = ["python_lib", "configuration_file_format", "json", "yaml", "toml"]

[proxy]
scheme = "http"
host = "127.0.0.1"
port = 8118
